### ISSUE TITLE
Scrollbar not Hidden

### ISSUE THREAD

**Issue by Zeyu-Xie** [Zeyu-Xie/Hydrangea-Jupyrender#2]
The internal CSS code below does not seem to work for hiding the scrollbar:

```CSS
::-webkit-scrollbar {
  display: none;
  width: 0;
  height: 0;
}

html, body {
  scrollbar-width: none;
  -ms-overflow-style: none;
  overflow: -moz-scrollbars-none;
}
```
